### ISSUE TITLE
Can't seem to compile properly

### ISSUE THREAD

**Issue by toiletflusher** [olauncher/olauncher#10]
![image](https://user-images.githubusercontent.com/80153347/189538432-8d2d6949-72a6-49a9-9121-e16f4b23d087.png)
Am i doing something wrong? I downloaded the source code from the latest release.
`Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\maven
Java version: 18.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"`

**Comment by bigfoot547** [comment]
Strange, it's complaining that the pom.xml isn't there. Is the project cloned correctly?
