### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by waterdragon78** [olauncher/olauncher#13]
Hi! I was trying to compile this, however I get this on apply patches.sh

fatal: destination path 'olauncher' already exists and is not an empty directory.
~/olauncher ~
fatal: remote upstream already exists.
fatal: ambiguous argument 'upstream/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: could not open '/Users/arbifox/launcher-patches/*.patch' for reading: No such file or directory
~
Patches did not apply cleanly to olauncher. Please fix.

how do I fix this?

Im on MacOS 10.14

**Comment by waterdragon78** [comment]
so I fixed that but now when using mvn I'm getting this:

Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher

**Comment by bigfoot547** [comment]
From what I can understand, that is an issue with your maven installation.

**Comment by waterdragon78** [comment]
Or where should I cd into to build it?

**Comment by waterdragon78** [comment]
Turns out macOS is just weird, thank you!
