### ISSUE TITLE
Remove ???-dev-07fccb9-dirty from top bar

### ISSUE THREAD

**Issue by waterdragon78** [olauncher/olauncher#14]
Hi! I compiled the redist and also the normal jar and when I open it I get this on the top.
<img width="451" alt="Screen Shot 2022-10-27 at 2 41 23 PM" src="https://user-images.githubusercontent.com/45146536/198372315-ed148512-e820-45bf-9aef-d5f5423a25b5.png">
is there a way to remove it like in the jar in releases?

**Comment by bigfoot547** [comment]
See `dev.figboot.olauncher.launcher.LauncherVersion`. Make sure you have a git tag created in your local olauncher repository.
