### ISSUE TITLE
Minecraft 1.18.2-forge-40.1.0 crashes on startup

### ISSUE THREAD

**Issue by NMLWright** [olauncher/olauncher#15]
![olaunchererror](https://user-images.githubusercontent.com/39932443/200665330-fb4ac651-362c-4bf9-9252-8d49dbeee70b.png)

**Comment by bigfoot547** [comment]
Hello. I managed to get a fix for this working, I will do a bit more testing, then prepare a hotfix. Thanks.

**Comment by bigfoot547** [comment]
Are you able to build the project from source? if so, try 43e00b4203e1f821e29230aa7a09a11b1302cf66 out.

**Comment by NMLWright** [comment]
I'm not sure how to build it from source. Can you provide me with a .jar?

**Comment by bigfoot547** [comment]
This is a build of e2b13b70dec21319bebdcad65b8e28d16c1b1b0c, which fixes a bug in the previous commit.

https://mega.nz/file/4xkEwJaR#4FRGeJu6K7c8OcMfWlckAFZt5ZgiSk6IXPvQ1YNdo2E

**Comment by bigfoot547** [comment]
Here's a build of e2b13b70dec21319bebdcad65b8e28d16c1b1b0c, I had to fix a bug in the previous commit.

https://mega.nz/file/4xkEwJaR#4FRGeJu6K7c8OcMfWlckAFZt5ZgiSk6IXPvQ1YNdo2E

File integrity:
```
SHA256: 46f4867afd68a639fb23973f0b0398f8a4a127e8dbcac1bb45a768a8cd65f8f8
SHA512: 03599bd025b22d25a4087e03bb8e05d5bbcf9a8a4a0017dbbd57f855be90978529e3bafdf0da8ca7d291ffad031c6c835f93b76487dcab56dd67a01f6b93ab0b
```

**Comment by NMLWright** [comment]
It works thank you

**Comment by bigfoot547** [comment]
Nice. Released a hotfix with the changes. Thank you for reporting.
