### ISSUE TITLE
Launcher can’t download Language and Sound / Music files

### ISSUE THREAD

**Issue by JanGamesHD** [olauncher/olauncher#24]
![IMG_2998](https://user-images.githubusercontent.com/64363088/213896074-df9a3cb2-0130-4ba4-a92a-2a7ccc00f965.jpeg)

The game starts, but there are no sounds and there are no languages in the language menu
![IMG_3003](https://user-images.githubusercontent.com/64363088/213896110-d1a3a5d3-62a7-4f2a-b8cf-f2dac647a702.jpeg)

(Sorry that I couldn’t use a screenshot)

**Comment by bigfoot547** [comment]
This issue has been fixed in 2390cbdba266b2ab74b936c236c6d642783c1df9.
