### ISSUE TITLE
OLauncher is unable to download Textures, Language, Sound and Music Files

### ISSUE THREAD

**Issue by samozoid** [olauncher/olauncher#25]
Olauncher is unable to download essential Language and Sound Files due to the location of Textures, Language, Sound and Music Files being changed in a recent launcher update. This change also happened server side and therefore breaks old launchers which use the previous asset servers. So when the launcher starts it attempts to download Textures, Language, Sound and Music Files but fails and eventually just launches Minecraft without them.

Launcher Log: https://pastebin.com/JSVYrmba

Game Output: https://pastebin.com/JxickDL3

Screenshot:  ![image](https://user-images.githubusercontent.com/85806291/214034310-763fb8e8-0f82-45a0-acc7-bfe27b8bb039.png)

**Comment by bigfoot547** [comment]
alright try out the new hotfix, that should work

**Comment by samozoid** [comment]
Thanks for fixing that! You where the first GitHub developer to fix something when I create an issue. It took almost two minutes but at least it worked! I will keep you notified if anything else happens.

**Comment by bigfoot547** [comment]
You're welcome, and thanks for the issue!

(Fixed in 2390cbdba266b2ab74b936c236c6d642783c1df9)
