### ISSUE TITLE
login with microsoft stuck load 

### ISSUE THREAD

**Issue by kuiito** [olauncher/olauncher#26]
when I did the login with microsoft it put me on a windows page where it auto logged me in the wrong account the one without minecraft and now its stuck forverer on login with microsoft and the windows page says The code has been received. You may now close this window.

**Comment by bigfoot547** [comment]
Yeah, this is a known issue. The current way the microsoft login is a little unsatisfactory, and there's not a lot I can do about it if I want the launcher to support java 8 and onward (which I do). The workaround for now would be to log into the "wrong" microsoft account, revoke OLauncher's access, and try again, this time choosing another account if possible.

Sorry for the weirdness.

**Comment by bigfoot547** [comment]
Tracked in #21
