### ISSUE TITLE
fix for the cobalt logo not loading

### ISSUE THREAD

**Issue by NotADinosaur** [olauncher/olauncher#29]
On the right sidebar, the scrolls logo loads but the cobalt logo does not.  
![620CF99A-90D3-4538-A5BC-C7940A45FA45](https://user-images.githubusercontent.com/76700400/222979364-d02c6e75-a712-4b2a-9d99-9f701b67b88d.jpeg)  
This can be fixed by changing the url the launcher uses to get the image from `https://assets.mojang.com/cobalt/cobalt_logo_150.PNG` to `https://assets.mojang.com/cobalt/cobalt_logo_150.png` (with a lowercase file extension).  
I’m making this an issue and not a pr because I don’t understand how these patches work and won’t pretend to, I’m not the one who figured this out about the url.

**Comment by bigfoot547** [comment]
thanks for reporting

**Comment by halotroop2288** [comment]
This is a problem with the website, not the launcher. Redirecting it from `https://mcupdate.tumblr.com` to `https://halotroop.github.io/MCUpdate` (or similar replacements) would be a good way for the launcher to fix issues with the blog.
If you want to create your own replacement, I've created a Jekyll template for MCUpdate that should work.
