### ISSUE TITLE
This happens everytime I try to load the game

### ISSUE THREAD

**Issue by CaidnAnimates** [olauncher/olauncher#3]
![Screenshot 2022-05-27 204441](https://user-images.githubusercontent.com/92276497/170803101-f22f23ef-b775-486b-a8b9-81c443fb2603.png)

**Comment by ZyrinDoc** [comment]
It seems that there might be an error with the Java Virtual Machine. Uninstall Java and reinstall from [here](https://java.com/en/download/). If that doesn't solve the problem, feel free to reply.

**Comment by bigfoot547** [comment]
How much RAM do you have? It seems java could not allocate the requisite 2 gigs to run the JVM.

**Comment by ZyrinDoc** [comment]
> How much RAM do you have? It seems java could not allocate the requisite 2 gigs to run the JVM.

I was thinking this since it was talking about how it couldn't reserve enough memory. It could be some privilege error or you just don't have enough allocated RAM.

**Comment by bigfoot547** [comment]
Yeah, I remember encountering this issue when testing the launcher on a VM with too little memory. I imagine this is the same issue.
