### ISSUE TITLE
Make a discord

### ISSUE THREAD

**Issue by Killer212** [olauncher/olauncher#30]
You should make a discord for the launcher, since it was tough to find the launcher and I had to search for a while.

**Comment by bigfoot547** [comment]
sure. I'll post an invite link when I make it. I may morph it into a server for all of my projects if I start making more stuff (planned).

**Comment by bigfoot547** [comment]
ok here you go, it's all set up mostly. https://discord.gg/zqYZknvYuZ

**Comment by bigfoot547** [comment]
closing since it's done
