### ISSUE TITLE
SUGGESTION: Allow renaming of the window

### ISSUE THREAD

**Issue by Ten2O** [olauncher/olauncher#35]
I want to get as authentic of an experience as possible. I've replaced the icon, but I cannot find a way to replace the name of the window from olauncher to Minecraft Launcher. Can you add an option for a custom window name?

**Comment by bigfoot547** [comment]
I suppose I could make it a java property. I'll see if I can work on this later today

**Comment by bigfoot547** [comment]
You can set the window title by passing the JVM argument `-Dnet.minecraft.launcher.WindowTitle="some window title"`

**Comment by Ten2O** [comment]
> You can set the window title by passing the JVM argument `-Dnet.minecraft.launcher.WindowTitle="some window title"`

How do you do this properly? It doesn't seem to run at all.

**Comment by bigfoot547** [comment]
Something like `java -Dnet.minecraft.launcher.WindowTitle="some window title" -jar olauncher.jar --workDir <your working directory>` should work. Make sure you're on `8edd53b` not the latest release.
