### ISSUE TITLE
have an installer

### ISSUE THREAD

**Issue by emeraldongithub** [olauncher/olauncher#36]
portable programs are a pain for me when i accidentally forget to put the program on the desktop

**Comment by JanGamesHD** [comment]
What’s wrong with moving the file to the desktop?

Does it create extra files there?
Maybe create a shortcut to the file

**Comment by emeraldongithub** [comment]
Nah I just always forget to move portable files somewhere else that’s all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Ten2O** [comment]
Even the original Minecraft old launcher was just a jar file. Though I think there was an installer available for as long as the launcher was current.

**Comment by notbronwyn** [comment]
just put a shortcut to it somewhere
