### ISSUE TITLE
Ram Issue

### ISSUE THREAD

**Issue by MP36ctrl** [olauncher/olauncher#37]
I allowed Java to use 10G of ram in the control panel,
when i put 10G in the Olauncher profile editor it wont let me load with this error message

Invalid maximum heap size: -Xmx8G
The specified size exceeds the maximum representable size.
In the regular MC launcher there is no issue which is why i feel like there is a bug, please let me know if im doing anything wrong, i really like the fact we can get the old launcher to work with ms accounts (I despise the new launcher cuz its slow)

**Comment by bigfoot547** [comment]
In the launcher log, near the top you should see a line like `System.getProperty('os.arch') == 'something'`. What is that something?

**Comment by MP36ctrl** [comment]
[22:45:32 INFO]: System.getProperty('os.arch') == 'x86' i got this

**Comment by bigfoot547** [comment]
Try starting the launcher using a 64-bit jvm. The java.com one is 32 bit and the launcher detects your architecture incorrectly.

**Comment by MP36ctrl** [comment]
im not sure how to do that ;-;

**Comment by bigfoot547** [comment]
Try eclipse temurin: https://adoptium.net/temurin/releases/?version=8
make sure to get the JRE for x64

**Comment by MP36ctrl** [comment]
it worked tysm

**Comment by bigfoot547** [comment]
you're welcome. I'm glad it works :)
