### ISSUE TITLE
EXE File?

### ISSUE THREAD

**Issue by Daisreich** [olauncher/olauncher#46]
title

**Comment by exrodev** [comment]
What is the issue here? Are you unable to start the launcher because it isn't an exe or are you requesting there to be an exe with the releases?

**Comment by Daisreich** [comment]
no i'm just asking if there will be an exe variant of the jar file

**Comment by Adahel** [comment]
See https://github.com/olauncher/olauncher/discussions/45! @Daisreich

**Comment by bigfoot547** [comment]
this is apparently very frequently requested. Maybe it's worth investigating making artifacts with something like Launch4j

**Comment by uptudev** [comment]
\>Released as a literal executable Java archive
"where .exe"

You literally cannot make this shit up lmao.
___
I agree with your position here. It makes little sense to wrap an executable JAR in a native executable binary, as it really defeats the purpose of the JAR format anyways, even disregarding all potential signing issues.

**Comment by bigfoot547** [comment]
yeah I guess this marks the end of the useful discussion in this issue. There are no plans for a .exe release. You will have to get by as you did in the olden days, when the actual official launcher was a .jar.
