### ISSUE TITLE
Olauncher Wont launch minecraft

### ISSUE THREAD

**Issue by CrimsonSiphyr** [olauncher/olauncher#47]
Every time i press play to play minecraft, it says its downloading a few things, but then it doesnt launch minecraft at all

**Comment by bigfoot547** [comment]
Can you show us the launcher log?

**Comment by Zombie287432874** [comment]
It's happening to me too and the log is blank

**Comment by bigfoot547** [comment]
launcher log, not game log (it's a different log)

**Comment by Zombie287432874** [comment]
Also here's a video

https://github.com/olauncher/olauncher/assets/137406732/d24b1be0-8dc7-40e7-af69-5a5cb422f91c

**Comment by Zombie287432874** [comment]
And here's the launcher log

**Comment by JanGamesHD** [comment]
> It's happening to me too and the game log is blank. Also here's a video. https://github.com/olauncher/olauncher/assets/137406732/d24b1be0-8dc7-40e7-af69-5a5cb422f91c I swiched to java 8 and the game log is Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap. I probably need to restart my pc.

You need 64 Bit Java to fix that error

**Comment by Zombie287432874** [comment]
> > It's happening to me too and the game log is blank. Also here's a video. https://github.com/olauncher/olauncher/assets/137406732/d24b1be0-8dc7-40e7-af69-5a5cb422f91c I swiched to java 8 and the game log is Error occurred during initialization of VM Could not reserve enough space for 2097152KB object heap. I probably need to restart my pc.
> 
> You need 64 Bit Java to fix that error

Ok

**Comment by bigfoot547** [comment]
I'm gonna assume this is no longer an issue. Please make a new issue if anything else breaks.
