### ISSUE TITLE
cant open olauncher

### ISSUE THREAD

**Issue by MacncheeseTTR** [olauncher/olauncher#48]
running arch linux with java 21.
Error: Could not find or load main class olauncher-1.7.2_10-redist.jar
Caused by: java.lang.ClassNotFoundException: olauncher-1.7.2_10-redist.jar

**Comment by bigfoot547** [comment]
For the record, this issue is caused by running a command like `java olauncher-1.7.2_10-redist.jar`, where the command assumes the jar file path to be a class name on the classpath to use as the main class. Make sure to specify `-jar`. Closing issue.
