### ISSUE TITLE
windows xp vm loads log in screen on vm

### ISSUE THREAD

**Issue by DONTDDOSME** [olauncher/olauncher#50]
i dont want to sign in i want to play minecraft!!
![Captura](https://github.com/olauncher/olauncher/assets/135388372/484c573b-b0d8-4581-818c-2d4662a3f89c)

**Comment by exrodev** [comment]
OLauncher doesn't support cracked/offline accounts. If you would like to launch Minecraft with OLauncher, please sign in or buy an account.

**Comment by DONTDDOSME** [comment]
dang it so classicube is better

**Comment by DONTDDOSME** [comment]
yeah it is very better i will uninstall it

**Comment by DONTDDOSME** [comment]
i made a a microsoft account i might use it very later when my main pcs is broken
