### ISSUE TITLE
XDG Base Directory

### ISSUE THREAD

**Issue by Doctor-Cpu** [olauncher/olauncher#54]
Currently everything is dumped inside inside .minecraft in the users home folder.
[While this was marked as a wont fix for the official launcher](https://bugs.mojang.com/browse/MCL-2563), this project could support it.
I don't suggest it be the default but still be checked it exists and it takes preference. Could be $XDG_DATA_HOME/minecraft or $XDG_DATA_HOME/olauncher with the default for $XDG_DATA_HOME being $USER/.local/share/.
I'm unsure if this is even feasible due to the project purely being patches but this would to an improvement as you can currently change the game directory path.

**Comment by bigfoot547** [comment]
good idea, I'll see if I can get a PR for this written at some point maybe

**Comment by bigfoot547** [comment]
Was just thinking about this again. How would this be functionally different from running the launcher with `--workDir "$HOME/.local/share/olauncher`?

**Comment by Doctor-Cpu** [comment]
> Was just thinking about this again. How would this be functionally different from running the launcher with `--workDir "$HOME/.local/share/olauncher`?

Ah this is close enough to what I was looking for. Thanks.
