### ISSUE TITLE
UI doesn't change size when the window is resized

### ISSUE THREAD

**Issue by theoparis** [olauncher/olauncher#59]
![image](https://github.com/olauncher/olauncher/assets/11761863/ab2abda8-53ee-4941-9b4c-1e09c6884576)

Not sure if this is something that can be fixed but I figured I'd create an issue just in case. I'm running this on Debian Linux.

**Comment by bigfoot547** [comment]
Hmm, I run debian testing/sid with i3 and haven't experienced this issue. What else can you tell me about your environment? JVM, java version, logs maybe? thanks for reporting

**Comment by theoparis** [comment]
Hmm it seems to be due to XWayland. I'm assuming this doesn't support wayland natively and I don't know if its possible to do that.

Java version is openjdk 21.0.2.

**Comment by bigfoot547** [comment]
Swing ideally should be independent of whether you use Wayland or X. Maybe your JVM's swing implementation just doesn't support XWayland. Try a different JVM maybe?
