### ISSUE TITLE
Still issues with Microsoft accounts

### ISSUE THREAD

**Issue by SpareEnderboy** [olauncher/olauncher#60]
#57 still having the issue of not being able to login with a microsoft account
![image](https://github.com/olauncher/olauncher/assets/113299492/b5ad428a-fc7f-410c-8fb7-32b422166fca)
`java.lang.RuntimeException: java.net.BindException: Address already in use: JVM_Bind`

_h e l p_

**Comment by bigfoot547** [comment]
hmm do you have the launcher open twice?

**Comment by SpareEnderboy** [comment]
> hmm do you have the launcher open twice?

no

**Comment by bigfoot547** [comment]
weird. I wonder what else could be using that port.

**Comment by kosei9987aaa** [comment]
my dont show error (it going to open authcomplete but after that it doesn't work at all)

**Comment by bigfoot547** [comment]
@kosei9987aaa Your issue sounds like it could be already reported in #52. Try the workaround mentioned in there and if it doesn't work, make a new issue.

**Comment by bigfoot547** [comment]
should be resolved with device code option added in v1.7.3, but that is currently bugged. It will be fixed in the next hotfix.
