### ISSUE TITLE
Regarding the new Java 21 requirement for 24w14a+

### ISSUE THREAD

**Issue by vico93** [olauncher/olauncher#67]
Well, Mojang just dropped [a new snapshot](https://minecraft.wiki/w/Java_Edition_24w14a) that upgrade the JRE version to 21.0.2.

I didn't had the time to test here, but i wonder if olauncher can download the appropriate JRE version and run the game (in those versions) or it will need to be worked on.

**Comment by bigfoot547** [comment]
It appears to download and run the runtime just fine! :) Thanks for bringing this to my attention. Please reopen the issue of some issues arise
