### ISSUE TITLE
Button says "Play Offline" even when logged in

### ISSUE THREAD

**Issue by bigfoot547** [olauncher/olauncher#70]
note that multiplayer still works when the launcher runs the game in this state

**Comment by bigfoot547** [comment]
I believe this was fixed in 50ec28cfd74922e3112b211cf7920221467b5660 but needs more testing

**Comment by FoxbitDreamtail** [comment]
the launcher starts for me like this and then it switches to play a minute or two later, so be patient. I am on launcher v1.7.3

**Comment by bigfoot547** [comment]
yeah it normally takes some time to log in, but there is also a bug with the device code flow that doesn't save your refresh token. It's fixed in 50ec28cfd74922e3112b211cf7920221467b5660, which will be included in the next hotfix.
