### ISSUE TITLE
Java VM could not be created

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [olauncher/olauncher#72]
After launching any Minecraft version within this launcher, the Game Output shows in the launcher telling me:
"Error occurred during initialization of VM
Could not reserve enough space for 3145728KB object heap"
Not sure why. The normal Minecraft Launcher from the Microsoft Store launches Minecraft just fine. Is there a solution?
I'm getting frustrated since I hate the modern launcher and used this for a good amount of time.

**Comment by JanGamesHD** [comment]
You most likely have a 32 Bit version of Java installed. Can you send the launcher log?

**Comment by ThunderboltCommunicationsCorp** [comment]
Alright where do I find the log?

**Comment by ThunderboltCommunicationsCorp** [comment]
This is the log
[Log.txt](https://github.com/olauncher/olauncher/files/14963084/Log.txt)

**Comment by bigfoot547** [comment]
possible duplicate of #3. your launcher logs are in the tab with the same name. See if you can send the top 20 or so lines here.

**Comment by bigfoot547** [comment]
yeah, you need to download 64 bit java (try java.com)

**Comment by ThunderboltCommunicationsCorp** [comment]
Alright I'll do that

**Comment by ThunderboltCommunicationsCorp** [comment]
Yes it got fixed with 64bit Java thank you for the help! 5 Stars from me!
