### ISSUE TITLE
Hide Unsupported Game Versions

### ISSUE THREAD

**Issue by FoxbitDreamtail** [olauncher/olauncher#77]
as the name suggests, would it not be possible to just use the java runtime that the launcher started with for minecraft and if the java version is incompatible with say java 8 classes then should the game versions not be hidden behind a toggle where you would need to specify or allow to download a copy of java 17(specifically for x64 computers)?

**Comment by bigfoot547** [comment]
> would it not be possible to just use the java runtime that the launcher started with for minecraft

not necessarily

> if the java version is incompatible with say java 8 classes then should the game versions not be hidden behind a toggle where you would need to specify or allow to download a copy of java 17

that's not really necessary because the launcher will already download the appropriate java runtime from Mojang as necessary. There's also not really a way to tell the version of the java runtime if it is specified explicitly in the profile settings, so the launcher can't actually determine class file version compatibility. It only knows what java version should be downloaded for a specific version of the game.

**Comment by FoxbitDreamtail** [comment]
then why not use that information to limit the supplied options for unsupported Operating systems? Windows xp for example never supported java 17 so it would be safe to hide all minecraft versions that rely on java 17 or above in windows xp.

**Comment by FoxbitDreamtail** [comment]
You know that instead of just saying random things you can actually back up your point and prove it, find a Java 17 version that works with Windows XP service pack 3, I dare you. If you can't, then stop spouting nonsense. As far as anyone here is concerned there is no such thing as a version of java 17 or Java 21 for that matter that supports Windows XP service pack 3 x86.

**Comment by bigfoot547** [comment]
This feature would introduce an annoying maintenance burden which simply is not worth the effort.

**Comment by bigfoot547** [comment]
> then stop spouting nonsense

https://github.com/olauncher/olauncher/issues/82#issuecomment-2147404325
