### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by JanGamesHD** [olauncher/olauncher#8]
How can I change the working directory

**Comment by bigfoot547** [comment]
You may change the working directory of the launcher with the `--workDir` argument. Something like `java -jar olauncher-xxx.jar --workDir /home/username/.olauncher`. Note that this directory is where the versions will be installed, libraries will be downloaded, and profile information is stored. It is not necessarily where screenshots, mods, resource packs and saves belong. They go in the respective working directories set for each profile.

**Comment by JanGamesHD** [comment]
Thank you. I’ll try that
