### ISSUE TITLE
[Suggestion] Add a convenient way to install and update modpacks.

### ISSUE THREAD

**Issue by YounesSamatta** [olauncher/olauncher#87]
It could be something similliar to prism launcher:
![prismlauncher_nfD7qC3oEX](https://github.com/olauncher/olauncher/assets/96547485/e84f6fba-8747-4be7-a2d2-fb6961dd09f9)

**Comment by bigfoot547** [comment]
Sorry, mod management features are not planned. It is recommended to use an external mod manager like ferium to manage mods and modpacks with olauncher.
