### ISSUE TITLE
Forge crash

### ISSUE THREAD

**Issue by Kradek200** [olauncher/olauncher#9]
For some reason Forge crashes for me with this launcher, vanilla boots up just fine

![e](https://user-images.githubusercontent.com/108480245/189531574-b481e367-e42e-4935-baf3-a15e814b4859.png)

**Comment by bigfoot547** [comment]
Strange. Try adding `--add-opens java.base/java.lang.invoke=ALL-UNNAMED` to the JVM arguments in the profile editor.

**Comment by Kradek200** [comment]
> Strange. Try adding `--add-opens java.base/java.lang.invoke=ALL-UNNAMED` to the JVM arguments in the profile editor.

![image](https://user-images.githubusercontent.com/108480245/190497316-0920840f-6a0a-4fd6-8e4a-2a9b1700ae8e.png)
Did it, Got this error.

this is my full JVM argument :

-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M--add-opens java.base/java.lang.invoke=ALL-UNNAMED

**Comment by bigfoot547** [comment]
There should be a space between `32M` and `--add-opens`, for a complete argument line like this: `-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M --add-opens java.base/java.lang.invoke=ALL-UNNAMED`.

Regardless, I think the issue probably has to do with how the launcher applies JVM arguments specified in local versions. I'm going to investigate this some more.

**Comment by bigfoot547** [comment]
Please let me know if the new hotfix has resolved this issue.
