### ISSUE TITLE
Sorry, but we couldn't connect to out servers.

### ISSUE THREAD

**Issue by waterdragon78** [olauncher/olauncher#90]
I've tried with my wifi and a vpn. no dice.
<img width="894" alt="Screenshot 2024-07-05 at 4 20 39 AM" src="https://github.com/olauncher/olauncher/assets/45146536/05241ff2-40ae-48cb-a304-7f08fbd60c3a">

**Comment by waterdragon78** [comment]
Running ping on this url also gives an error. Perhaps a microsoft issue.
<img width="832" alt="Screenshot 2024-07-05 at 4 23 00 AM" src="https://github.com/olauncher/olauncher/assets/45146536/2aea4ec3-cd0f-4375-8cce-6eae5666b1db">

**Comment by bigfoot547** [comment]
there are a few reasons why this error might appear. What is the exception info you get when you run the launcher from the terminal?

**Comment by bigfoot547** [comment]
No follow-up in a month, and likely an account issue.

**Comment by bigfoot547** [comment]
that error indicates you're using the wrong microsoft account. use one that owns the game
