### ISSUE TITLE
Possibly make bedrock an option?

### ISSUE THREAD

**Issue by TheDolphinSlayer** [olauncher/olauncher#91]
I know this is annoying, and thank you for all the work you've done already. It's just back then me and my friends would play luckyislands on cubecraft and minecraft had this classic launcher But, only bedrock has it with multiplayer. It's just weird memories that I like to relive.

**Comment by bigfoot547** [comment]
This isn't really possible because bedrock edition does not require a launcher (it collects resources and does authentication itself). sorry
