### ISSUE TITLE
Google play depencies after update

### ISSUE THREAD

**Issue by jonkerw85** [olauncher/olauncher#94]
Best, I updated Olauncher today using APKUpdater. Somehow, the new version depends on Google Play Services, which I do not have. I run LineageOS AOSP without Google Play Services.
![Screenshot_20240827-141021_Olauncher](https://github.com/user-attachments/assets/9b8b0cab-09e8-464b-8c9d-15056610080c)

**Comment by JanGamesHD** [comment]
You are looking for another olauncher project on GitHub.
This one is about a Minecraft Launcher.

**Comment by jonkerw85** [comment]
Haha, thnx, you are right, thnx!
