### ISSUE TITLE
[Suggestion] Toggle: Keep Launcher Open After Game Launch

### ISSUE THREAD

**Issue by JoLiKMC** [olauncher/olauncher#98]
### What is your suggestion?
I wish that *OLauncher* had an option which would keep the launcher client open after attempting to launch a game.

### How would this benefit users?
This would be very handy for testing mods, mod packs, data packs, and other things which require the user to re-launch the game.

### Can you tell us anything else?
Typically, when launching *Minecraft* through most launchers, one of two things will happen:
- *Minecraft* opens and runs correctly, causing the launcher to close.
- *Minecraft* crashes and re-opens the launcher.
When updating mods and mod packs, I often find myself having to troubleshoot my collection one-by-one.  If the client crashes due to a bad mod or something, I can re-launch it through the launcher very quickly and easily.  If it works properly due to me *removing* a bad mod, though, I have to re-open the launcher.

In the standalone official launcher (and probably the Microsoft Store one), one can ask the launcher not to close itself after it tries to open a session of *Minecraft*.  I'd love to see this function added to *OLauncher*.  It'd be really helpful on "update day" for me, and hopefully for others!

As always, thank you for your hard work!

**Comment by bigfoot547** [comment]
Thanks for the issue! This feature already exists in OLauncher. You can access it in the profile editor (it's called "Launcher Visibility" under "Profile Info" in the window).

**Comment by JoLiKMC** [comment]
…!  Oh!  There it is!  Well, I apologize for that one.  I don't know why I didn't see that before…

Cheers!
