### ISSUE TITLE
Menu button becomes defunct occasionally after use

### ISSUE THREAD

**Issue by Janibal101** [olauncher/olauncher#99]
Haven't pinned down the exact conditions that cause this over the year that I've had this issue. But, when it happens, I have to switch to the the standard launcher in settings and back to Olauncher or restart my phone to fix it. The menu button refers to the square button in the OS tray when using the 3 button (not gesture) controls.

**Comment by JanGamesHD** [comment]
You should be able to close this issue. I'm not sure if you can delete it, maybe @bigfoot547 can.
